### ISSUE TITLE
Chars length in webapp

### ISSUE THREAD

**Issue by bdwyer2** [IBM/MAX-Review-Text-Generator#10]
In the web app the `chars` variable is set to `0` by default, not `100`

![screen shot 2018-08-16 at 1 22 08 pm](https://user-images.githubusercontent.com/19673623/44232997-83c8c600-a157-11e8-8e9e-35734def9bd1.png)

**Comment by MLnick** [comment]
The Swagger UI generates an example value as shown, but for a numerical value if you don't specify an example value (which you can do on the API data model fields as a named arg) then it default to `0`.

However the API itself does default to `100`: 
https://github.com/IBM/MAX-Review-Text-Generator/blob/master/api/model.py#L27

**Comment by MLnick** [comment]
This does however raise the issue that we currently don't populate these example values (to illustrate example request / response objects), and we should do that for better API doc.

cc @ptitzler @djalova @ajbozarth @gdequeiroz
